name: Code Analysis
on:
  push:
    branches: [main, main-v1, main-v2]
  pull_request:
    branches: [main, main-v1, main-v2]
  schedule:
    - cron: '0 7 * * 3'

permissions: read-all

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1.1.3
        with:
          config-file: ./.github/codeql-config.yml
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1.1.3
