name: Dependency Analysis
on:
  schedule:
    - cron: "0 0 * * 0"

permissions: read-all

jobs:
  npm-audit:
    name: Audit npm on ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - main-v1
          - main-v2
          - main
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v1.4.3
        with:
          egress-policy: block
          allowed-endpoints: >
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            registry.npmjs.org:443
            si05acprodeus1file1.blob.core.windows.net:443
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ matrix.version }}
      - name: Install Node.js
        uses: actions/setup-node@v3.2.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Initialize repository
        run: npm ci
      - name: Audit npm dependencies
        run: npm run audit
