name: Update
on:
  push:
    branches: [main, main-v1, main-v2]

permissions: read-all

jobs:
  lib:
    name: lib/index.js
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v1.4.1
        with:
          egress-policy: audit
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
      - name: Install Node.js
        uses: actions/setup-node@v3.1.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm ci
      - name: Build lib/index.js
        run: npm run build
      - name: Commit and Push Updated lib/index.js
        uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
          commit_message: "chore: update lib/index.js"
          commit_options: "--no-verify"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
