name: Update
on:
  push:
    branches: [main, main-v1]

permissions: read-all

jobs:
  lib:
    name: lib/index.js
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
      - name: Cache Dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build lib/index.js
        run: npm run build
      - name: Commit and Push Updated lib/index.js
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "chore: update lib/index.js"
          commit_options: "--no-verify"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
